# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updateTime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('title', models.TextField(max_length=256, verbose_name='标题')),
            ],
        ),
    ]
