# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30, verbose_name='姓')),
                ('lastName', models.CharField(max_length=30, verbose_name='名')),
            ],
        ),
    ]
